name: Static Analysis

on: ['push', 'pull_request']

jobs:
  pint:
    runs-on: ubuntu-latest

    name: Pint

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: zip
          coverage: none

      - name: Install PHP dependencies
        uses: ramsey/composer-install@v1
        with:
          dependency-versions: highest
          composer-options: "--prefer-dist"

      - name: Install Pint
        run: composer global require laravel/pint --dev

      - name: Run Pint
        run: pint --test --ansi
